[[plugin]]
id = "vabyz971/monitor"
name = "Monitor Dashboard"
version = "0.4.2"
min_noctalia = "5.0.0"
author = "Vabyz971"
license = "MIT"
tags = ["monitoring"]
icon = "device-heart-monitor"
description = "System and application activity monitor"
