id = "vabyz971/monitor"
name = "Monitor Dashboard"
version = "0.3.2"
min_noctalia = "5.0.0"
author = "Vabyz971"
license = "MIT"
dependencies = []
tags = ["monitoring"]
icon = "device-heart-monitor"
description = "System and application activity monitor"

[[panel]]
id              = "monitor"
entry           = "monitor.luau"
width           = 1280
height          = 720
placement       = "attached"
position        = "auto"

[[service]]
id = "system-monitor"
entry = "service.luau"

[[widget]]
id = "widget"
entry = "widget.luau"

    [[widget.setting]]
    key = "glyph"
    type = "glyph"
    label_key = "settings.widget.glyph.label"
    description_key = "settings.widget.glyph.description"
    default = "device-heart-monitor"

    [[widget.setting]]
    key = "show_widget_text"
    type = "bool"
    label_key = "settings.widget.show_widget_text.label"
    description_key = "settings.widget.show_widget_text.description"
    default = true

    [[widget.setting]]
    key = "use_emoji_tooltip"
    type = "bool"
    label_key = "settings.widget.use_emoji.label"
    description_key = "settings.widget.use_emoji.description"
    default = true

    [[widget.setting]]
    key = "show_stats_in_bar"
    type = "bool"
    label_key = "settings.widget.show_stats.label"
    description_key = "settings.widget.show_stats.description"
    default = false


[[setting]]
key         = "update_interval"
type        = "double"
label_key   = "settings.update_interval.label"
description_key = "settings.update_interval.description"
default     = 1
min         = 1
max         = 5
